name: release

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'ghcr.io/${{ github.repository_owner }}/graphql'

    steps:
      - uses: actions/checkout@v3
